name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Set up Docker buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Define environment variables for ECR
    - name: Configure variables
      run: |
        echo "REPO_NAME=my-app-repo" >> $GITHUB_ENV
        echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG .

    # Push Docker image to Amazon ECR
    - name: Push Docker image to ECR
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG

    # Confirm the image was pushed
    - name: Verify image in ECR
      run: |
        aws ecr describe-images --repository-name $REPO_NAME --region $AWS_REGION
